version: '3.9'

services:
  web:
    build: ./nginx
    container_name: web_nginx
    ports:
      - "8080:80"
    depends_on:
      - cache

  cache:
    image: redis:alpine
    container_name: redis_cache
    volumes:
      - redis_data:/data

volumes:
  redis_data: